---
title: "Class07"
author: "Isobel Bartels"
date: "2026-09-16"
output: html_document:

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Answering Question about 
```{r answer to q}
con = DBI::dbConnect(RSQLite::SQLite(), "../data/scout.db")
postings = DBI::dbReadTable(con, "scout_postings") |> tibble::as_tibble()
DBI::dbDisconnect(con)

jobs = postings |>
  dplyr::select(company, title, location_state, remote, category, posted_at, last_seen_at) |>
  dplyr::mutate(dplyr::across(dplyr::ends_with("_at"), as.Date),
                days_open = as.numeric(last_seen_at - posted_at))
jobs  

#Q1 --Which cat is remote friendly
# to answer that, the logic would be as follows"
# Find the number of jobs per category 
#normalize the number of remote jobs per category by diviing the total jobs 

jobs |>
  # i want to move from the unit of analysis being a job posting to a category 
  dplyr::group_by(category) |>
  dplyr::summarise(
    postings = dplyr::n(),
    remote_share = mean(remote)
  )
#remind me to show you how to compute remote)share diff in next class

#based on vote in class I will deviate from the answer in the slide
#by showig the combination of cateogry and state

jobs |> 
  dplyr::group_by(category, location_state)
  dplyr::summarise(
    postings = dplyr,
    remote_share = mean(remote) |> round(digits = 2)
  ) |>
  dplyr::arrange(dplyr::desc(remote_share)) |>
  na.omit(()) #to drop the location_state == NA and any other rows that contain NA 
```

```{r}
con = DBI::dbConnect(RSQLite::SQLite(), "../data/midwest_airbnb.db")
listings = DBI::dbReadTable(con, "listings") |>
  tibble::as_tibble()
DBI::dbDisconnect(con)
dplyr::glimpse(listings)

#1. How many listings per city ?
##if the answer is purely based on last class I can group by city and then count the number of lisitngs in each city 

listings |> dplyr::group_by(city) |> dplyr::summarise(count = dplyr::n())
#alternativley, the short cut for the code above
listings |> dplyr::count(city) #count dooes group by then n()

#the other option is to simply count the number of times each city occured in the col city 

table(listings$city) #returns a named vctor vs above we get a data.frame/tibble 
```



