---
title: "class08"
author: "Isobel Bartels"
date: "2026-09-21"
output: 
html_document:
  toc: true 
  toc_float: true
  number_sections: true

---

```{r api_intro}
httr2::request("https://data.cincinnati-oh.gov/resource/rvmt-pkmq.json") |>
  httr2::req_url_query("$limit" = 5) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON() -> cincy_crashes
```

#FRED API
```{r}
httr2::request("https://api.stlouisfed.org/fred/series/observations") |>
  httr2::req_url_query(
    series_id = "IHLIDXUSOH",
    api_key = Sys.getenv("FRED_API_KEY"),
    file_type = "json"
  ) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON() -> ohio_jobs

jobs_df = ohio_jobs[[13]]
#to get data from September 1, 2026
#(a)get all data and then filtr the rows that I want
#not the most efficent but correct
dplyr::glimpse(jobs_df) #realized thatdate is a chr
jobs_df |>
  dplyr::mutate(
    date = lubridate::ymd(date)
  ) |>
  #used filter to find all dates that are >= sep 01, 2026
  dplyr::filter(date >= '2026-09-01') -> jobs_df_mod
```

```{r}
#[b] use api since it has observation start
httr2::request("https://api.stlouisfed.org/fred/series/observations") |>
  httr2::req_url_query(
    series_id = "IHLIDXUSOH",
    api_key = Sys.getenv("FRED_API_KEY"),
    file_type = "json",
    observation_start="2026-09-01"
  ) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON() -> ohio_jobs_sep_2026
```

```{r}
httr2::request("https://data.usajobs.gov/api/search") |>
  httr2::req_url_query(Keyword = "Data Analyst", ResultsPerPage = 500) |>
  httr2::req_headers(
    Host = "data.usajobs.gov",
    "User-Agent" = "barteli@miamioh.edu",
    "Authorization-Key" = Sys.getenv("USAJOBS_API_KEY")
  ) |>
  httr2::req_perform() |>
  httr2::resp_body_string() |>
  jsonlite::fromJSON(flatten = TRUE) -> usa_jobs_list

usa_df = usa_jobs_list$SearchResult$SearchResultItems

jobs_small = usa_df |>
  dplyr::select(
    title = MatchedObjectDescriptor.PositionTitle,
    department = MatchedObjectDescriptor.DepartmentName,
    agency = MatchedObjectDescriptor.OrganizationName,
    location = MatchedObjectDescriptor.PositionLocationDisplay,
    closes = MatchedObjectDescriptor.ApplicationCloseDate
  )

##Answer based on Query 
nrow(jobs_small)
table(jobs_small$department) |> sort(decreasing = T) |> head(3)
jobs_small |> dplyr::count(department) |> dplyr::arrange(dplyr::desc(n)) |> head(3)

index_data_analyst = jobs_small$title |> 
  stringr::str_detect(pattern = 'Data Analyst|Data Analytics')
jobs = jobs_small
```


